### ISSUE TITLE
Uninstall packages that aren't in pageage.json

### ISSUE THREAD

**Issue by jwerre** [mgol/check-dependencies#23]
I use this as part of my deployment package to ensure my packages are installed — it works great! It would be nice if they uninstalled packages that are no longer needed.

**Comment by mgol** [comment]
There's the [onlySpecified](https://github.com/mgol/check-dependencies#onlyspecified) flag but it doesn't work with npm 3, unfortunately. My goal for this module was to be fast; the `npm ls` command already provides the info about excessive dependencies so I could have used that except that it's slow, it takes many seconds to complete on a large project.

That's why this module is ignoring the npm virtual package tree but instead just goes to `node_modules`, enters every directory with a `package.json` there and checks if versions match. With npm 3 packages are deduped by default which means `node_modules` contains many packages not directly specified in `package.json`. I don't think there's an easy way to avoid it, that's why I added a note to `onlySpecified` to not use it with npm 3.

One thing I could do is add a flag that would invoke `npm prune && npm install` instead of `npm install` when there are packages missing or in wrong versions; that wouldn't prune packages if you already have all that's required and just have a few extra unneeded packages. Would that help you or not? I don't see another way (I'm open to suggestions if you know sth, though)/

**Comment by mgol** [comment]
No response so I'll close it now.
