### ISSUE TITLE
Prototype Pollution issue in bower config dependency

### ISSUE THREAD

**Issue by martijnkorteweg** [mgol/check-dependencies#41]
Hi here,

Could you please look at the vulnerability. Not really sure if bower is still used in your project anyways.

Package       │ minimist 
Patched in    │ >=0.2.1 <1.0.0 || >=1.2.3
Dependency of │ check-dependencies [dev]
Path          │ check-dependencies > bower-config > optimist > minimist 
More info     │ https://npmjs.com/advisories/1179

**Comment by mgol** [comment]
Thanks for the report. The `bower-config` package is used to check whether the bower default directory for packages wasn't changed. Since the package was last updated 3 years ago, I'm not sure if it will ever see another update...

I'll need to think about it. Maybe it's time to drop Bower support but I'll need a major version bump for this.

**Comment by mgol** [comment]
The config resolution logic is complex enough that it's not easy to drop the package without dropping Bower: https://bower.io/docs/config/

**Comment by mgol** [comment]
The issue was fixed in `bower-config` in version `1.4.2`:
https://github.com/bower/bower/blob/master/packages/bower-config/CHANGELOG.md#142
Since `check-dependencies` specifies a version range `^1.4.0`:
https://github.com/mgol/check-dependencies/blob/1.1.0/package.json#L31
so it's enough to reinstall dependencies after removing a lock file to resolve the issue.

Thanks for reporting it to `bower-config`! Closing.

**Comment by martijnkorteweg** [comment]
It seems the minimist package is still being used by check-dependencies package.json. could this be removed now?

**Comment by mgol** [comment]
@martijnkorteweg It can't be removed as it's used in https://github.com/mgol/check-dependencies/blob/master/bin/cli.js. But I've specified a semver version range so it will pick up latest `minimist` security updates.
